name: enviro-sensor-hub PlatformIO CI

on:
  push:
    branches: [ Feature/github-actions-workflow ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install PlatformIO
      run: pip install platformio

    - name: Install cpplint
      run: pip install

    - name: Run cpplint
      run: |
        find src include lib test -name "*.cpp" -o -name "*.h" | \
        xargs cpplint --linelength=120 --filter=-legal/copyright,-build/include_subdir

    - name: Run PlatformIO build
      run: platformio run
